//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adisyonlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adisyonlar()
        {
            this.AdisyonHareketler = new HashSet<AdisyonHareketler>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MasaId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdisyonHareketler> AdisyonHareketler { get; set; }
        public virtual Masalar Masalar { get; set; }
    }
}
