//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdisyonHareketler
    {
        public int Id { get; set; }
        public Nullable<int> AdisyonId { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
    
        public virtual Adisyonlar Adisyonlar { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
