//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeOtomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CafeOtomasyonEntities : DbContext
    {
        public CafeOtomasyonEntities()
            : base("name=CafeOtomasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdisyonHareketler> AdisyonHareketler { get; set; }
        public virtual DbSet<Adisyonlar> Adisyonlar { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Masalar> Masalar { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
    }
}
